"""add player_season_teams and consensus_adp

Revision ID: 508c3c0ce8bb
Revises: ae0f2805853f
Create Date: 2026-08-04 00:12:56.864868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508c3c0ce8bb'
down_revision: Union[str, Sequence[str], None] = 'ae0f2805853f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consensus_adp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scoring_format', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('name_raw', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('nfl_team', sa.String(), nullable=True),
    sa.Column('adp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consensus_adp_season'), 'consensus_adp', ['season'], unique=False)
    op.create_table('player_season_teams',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('nfl_team', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_season_teams')
    op.drop_index(op.f('ix_consensus_adp_season'), table_name='consensus_adp')
    op.drop_table('consensus_adp')
    # ### end Alembic commands ###
