"""add player_injury_reports

Revision ID: b87a30ec067b
Revises: 508c3c0ce8bb
Create Date: 2026-08-04 00:43:25.229862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87a30ec067b'
down_revision: Union[str, Sequence[str], None] = '508c3c0ce8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_injury_reports',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('report_status', sa.String(), nullable=False),
    sa.Column('primary_injury', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season', 'week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_injury_reports')
    # ### end Alembic commands ###
