"""
Step 6 - assemble results/REPORT_DATA.md.

One document, organised in the order the handout asks for the write-up, that
pairs every number with the figure that shows it and the table it came from.
It is a worksheet for writing the report, not the report itself: it states what
the data shows and flags what is shaky, and leaves the prose to you.
"""

import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lab2lib as L

OUT = os.path.join(L.ROOT, "results", "REPORT_DATA.md")


def md_table(df, cols=None, floatfmt="{:.4g}"):
    d = df[cols] if cols else df
    head = "| " + " | ".join(str(c) for c in d.columns) + " |"
    rule = "|" + "|".join("---" for _ in d.columns) + "|"
    rows = []
    for r in d.itertuples(index=False):
        cells = []
        for v in r:
            if isinstance(v, float) and np.isfinite(v):
                cells.append(floatfmt.format(v))
            elif v is None or (isinstance(v, float) and not np.isfinite(v)):
                cells.append("-")
            else:
                cells.append(str(v))
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join([head, rule] + rows)


def main():
    T = L.TABLES
    bt = pd.read_csv(os.path.join(T, "bridge_trials.csv"))
    bA = pd.read_csv(os.path.join(T, "bridge_partA.csv"))
    bB = pd.read_csv(os.path.join(T, "bridge_partB.csv"))
    bc = pd.read_csv(os.path.join(T, "bridge_commands.csv"))
    tt = pd.read_csv(os.path.join(T, "tower_trials.csv"))
    ts = pd.read_csv(os.path.join(T, "tower_summary.csv"))
    fq = pd.read_csv(os.path.join(T, "design_frequencies.csv"))
    pr = pd.read_csv(os.path.join(T, "design_predictions.csv"))
    ib = pd.read_csv(os.path.join(T, "inventory_bridge.csv"))

    A = []
    w = A.append
    w("# Lab 2 - Input Shaping: reduced data for the write-up\n")
    w("Generated by `analysis/run_all.py`. Tables in `results/tables/`, figures in "
      "`results/figures/`, data-quality screen in `results/DATA_QUALITY.md`.\n")
    w("**Headline metric.** Residual oscillation is reported as `amp_pp`, the largest "
      "peak-to-peak payload swing within the first four measured periods after the "
      "trolley stops (bridge) or within five mode-1 periods of the vision record "
      "(tower). Peak-to-peak rather than amplitude, and capped at a fixed number of "
      "periods so trials with different record lengths stay comparable.\n")

    # ------------------------------------------------------------------ A ---
    w("---\n\n## Bridge crane, Part A - variation in move distance\n")
    w("0.8 m cable, 100 % speed, trolley axis. Figures 01 and 02.\n")
    w(md_table(bA, ["shaper", "tf_ms", "n", "dist_mm", "amp_pp_mm", "amp_pp_sd",
                    "rms_mm", "pct_of_unshaped", "pct_reduction", "T_meas_s",
                    "T_theory_s", "n_short_window"]))
    w("")
    wA, TA = L.pendulum_freq(0.8)
    u1100 = bA[(bA.shaper == "Unshaped") & (bA.tf_ms == 1100)].amp_pp_mm.iloc[0]
    u1600 = bA[(bA.shaper == "Unshaped") & (bA.tf_ms == 1600)].amp_pp_mm.iloc[0]
    u2000 = bA[(bA.shaper == "Unshaped") & (bA.tf_ms == 2000)].amp_pp_mm.iloc[0]
    w(f"**The trend to explain.** The unshaped residual falls steeply with move "
      f"distance: {u1100:.0f} mm at tf = 1100 ms, {u1600:.0f} mm at 1600 ms, "
      f"{u2000:.0f} mm at 2000 ms. That is not damping - it is the frequency "
      f"response of the velocity pulse itself. A pulse of length tf excites a "
      f"residual proportional to |sin(w*tf/2)|, which is zero whenever tf is an "
      f"integer number of periods. With a 0.8 m cable T = {TA:.3f} s, so "
      f"tf = 1100 ms sits at tf/T = {1.1/TA:.2f} (near the worst case at 0.5) while "
      f"tf = 2000 ms sits at tf/T = {2.0/TA:.2f} (near the null at 1.0). Figure 02 "
      f"plots the measured points on that curve.\n")
    w("**The ZV design.** Delay 0.90 s, amplitudes 0.50/0.50, read back from the "
      f"measured velocity of every trial. For the 0.8 m cable actually used, "
      f"T/2 = {TA/2:.3f} s, so 0.90 s is the correct half-period - the shaper was "
      "designed at the system frequency, and that is the whole justification "
      "needed here.\n")
    zv = bA[bA.shaper == "ZV"]
    w(f"**What the ZV bought.** Residual drops to "
      f"{zv.amp_pp_mm.min():.0f}-{zv.amp_pp_mm.max():.0f} mm at every tf, i.e. "
      f"{zv.pct_of_unshaped.min():.0f}-{zv.pct_of_unshaped.max():.0f} % of unshaped "
      "(77-92 % reduction), and - the important part - it is *flat* in tf. The "
      "unshaped residual varies by 4x across these three move distances; the "
      "shaped residual does not. Input shaping removes the sensitivity to move "
      "distance, not just the vibration at one distance.\n")
    w("**Limits worth stating.** The ZV residual (12-30 mm p-p) is 10-20x the 1 mm "
      "deflection-sensor resolution, so it is real vibration and not noise, but it "
      "is far above the ~0.5 % the ideal shaper predicts. The gap is execution, not "
      "design: finite trolley acceleration, friction at breakaway, and a cable "
      "length known only to a few mm.\n")

    # ------------------------------------------------------------------ B ---
    w("---\n\n## Bridge crane, Part B - variation in system frequency\n")
    w("tf = 1500 ms, cable 600 / 900 / 1200 mm. Figures 03, 04, 05, 06.\n")
    w(md_table(bB, ["shaper", "cable_nom_mm", "n", "dist_mm", "rise_s", "amp_pp_mm",
                    "amp_pp_sd", "rms_mm", "pct_of_unshaped", "pct_reduction",
                    "T_meas_s", "T_theory_s"]))
    w("")
    w("Measured periods match the single-pendulum model to better than 2 % at every "
      "cable length, which validates the frequencies the shapers were designed at.\n")
    w_lo = L.pendulum_freq(1.2)[0]
    w_hi = L.pendulum_freq(0.6)[0]
    w_mid = 0.5 * (w_lo + w_hi)
    w(f"**The ZV design, and why 0.91 s.** The three cable lengths span "
      f"w = {w_lo:.3f} to {w_hi:.3f} rad/s, a 1.41:1 range. The delay actually used, "
      f"0.91 s, is pi divided by the *arithmetic mean of the two extreme "
      f"frequencies*: pi/{w_mid:.3f} = {np.pi/w_mid:.3f} s. That is the right way to "
      f"centre a single shaper over a known frequency range - it puts the notch in "
      f"the middle of the range in frequency, which balances the worst-case error at "
      f"the two ends, rather than centring on the middle cable length "
      f"(0.9 m -> {L.pendulum_freq(0.9)[1]/2:.3f} s), which would leave the 0.6 m "
      f"case much worse off. Figure 05 shows the resulting notch sitting between the "
      f"0.6 m and 1.2 m markers.\n")
    w("**The ZVD problem - read this before writing about the robust shaper.** The "
      "nine trials named ZVD were *not* run with a ZVD. Reconstructing the applied "
      "command from the measured trolley velocity (the GUI logs no command) gives "
      "amplitudes **[0.25, 0.50, 0.50]** at delays [0, 0.91, 1.82] s on all nine, "
      "summing to 1.25 instead of 1.00. The third impulse was entered as 0.50 "
      "instead of 0.25. Two consequences, both visible in the data:\n")
    w("  1. The move is 27 % longer - "
      f"{bB[bB.shaper=='ZVD'].dist_mm.mean():.0f} mm against "
      f"{bB[bB.shaper=='ZV'].dist_mm.mean():.0f} mm for the ZV at the same tf - "
      "because the command carries 1.25x the area.")
    w("  2. More importantly, the sensitivity curve no longer has a notch. At the "
      "design frequency the residual is 0.25/1.25 = **20 %**, not 0. Figure 05 shows "
      "the as-run ZVD curve bottoming out near 20 % while the textbook "
      "[0.25, 0.50, 0.25] curve goes to zero.\n")
    pB = pr[(pr.rig == "Bridge") & (pr.part == "B")]
    w("Predicted residual as a fraction of unshaped, at each cable length:\n")
    w(md_table(pB, ["shaper", "cable_m", "w_rad_s", "V_rel_vs_unshaped"]))
    w("")
    w("This is what makes the measured result interpretable: measured ZVD gives "
      f"{bB[bB.shaper=='ZVD'].pct_of_unshaped.min():.0f}-"
      f"{bB[bB.shaper=='ZVD'].pct_of_unshaped.max():.0f} % of unshaped and measured "
      f"ZV gives {bB[bB.shaper=='ZV'].pct_of_unshaped.min():.0f}-"
      f"{bB[bB.shaper=='ZV'].pct_of_unshaped.max():.0f} %, so the *robust shaper did "
      "not beat the ZV*. With the textbook amplitudes theory says it should have "
      "(7 % vs 27 % at the extremes). The honest conclusion is that the ZVD trials "
      "measure a mis-entered three-impulse shaper, and they agree with theory once "
      "the as-run amplitudes are used. Say that rather than reporting a ZVD that "
      "underperformed.\n")
    w("**The robustness story that does survive.** Compare the *shape* of the two "
      "curves in Figure 04: the ZV is best at 0.9 m (nearest its design frequency, "
      f"{bB[(bB.shaper=='ZV')&(bB.cable_nom_mm==900)].pct_of_unshaped.iloc[0]:.0f} % "
      "of unshaped) and degrades at both ends, worst at 1.2 m "
      f"({bB[(bB.shaper=='ZV')&(bB.cable_nom_mm==1200)].pct_of_unshaped.iloc[0]:.0f} %). "
      "The three-impulse shaper is flatter across the range even mis-entered - its "
      "spread across cable lengths is smaller than the ZV's. That is the robustness "
      "trade-off the lab is about, and the cost is duration: rise time "
      f"{bB[bB.shaper=='ZVD'].rise_s.mean():.2f} s against "
      f"{bB[bB.shaper=='ZV'].rise_s.mean():.2f} s for the ZV and "
      f"{bB[bB.shaper=='Unshaped'].rise_s.mean():.2f} s unshaped.\n")
    w("**Caveat on the Part B baseline.** Only one unshaped trial survived screening "
      "at 600 mm (see DATA_QUALITY.md), so the percentages at that cable length rest "
      "on a single baseline run.\n")

    # -------------------------------------------------------------- tower ---
    w("---\n\n## Mobile tower crane\n")
    w("L1 (hoist) = 0.6 m, L2 = 0.2 m, tf = 4000 ms, 100 % slew, trolley at "
      "500 / 700 / 900 mm. Figures 07-12 and 14-17.\n")
    w("Residual swing is scored over three mode-1 periods starting 0.2 s after the "
      "slew stops, on the vision stream aligned onto the motion clock. A separate "
      "`*_peak_pp_deg` column reports the largest swing DURING the move plus a 3 s "
      "tail - the transient the operator sees - because a shaper can win on one and "
      "lose on the other.\n")
    w("### Double-pendulum frequencies\n")
    ftow = fq[fq.rig == "Tower"]
    w(md_table(ftow, ["config", "w_rad_s", "f_hz", "T_s", "half_T_s"]))
    w("")
    w(f"Measured from the swing spectra: f1 = {tt.tan_m1_f_meas_hz.mean():.3f} Hz and "
      f"f2 = {tt.tan_m2_f_meas_hz.mean():.3f} Hz, i.e. "
      f"{tt.tan_m1_f_err_pct.mean():.0f} % and {tt.tan_m2_f_err_pct.mean():.0f} % "
      "below the linearised model (Figure 11). Both modes are clearly present in "
      "every trial. The shapers were designed at the model frequencies, so they were "
      "tuned about 10 % high - that alone caps how much cancellation was achievable "
      "and is the first thing to cite when explaining imperfect results.\n")
    w("### Residual swing by shaper and radius\n")
    w(md_table(tt, ["shaper", "trolley_nom_mm", "actual_travel_deg", "tan_amp_pp_rad",
                    "pct_tan", "tan_m1_amp_pp_rad", "pct_tan_m1", "tan_m2_amp_pp_rad",
                    "pct_tan_m2", "rad_amp_pp_rad", "pct_rad"]))
    w("")
    w("### Averaged over the three radii\n")
    w(md_table(ts, ["shaper", "n", "shaper_dur_s", "actual_travel_deg",
                    "tan_amp_pp_rad", "pct_tan", "tan_m1_rad", "pct_tan_m1",
                    "tan_m2_rad", "pct_tan_m2", "rad_amp_pp_rad", "pct_rad"]))
    w("")
    w("### Answers to the four questions the handout asks\n")
    un = tt[tt.shaper == "Unshaped"].sort_values("trolley_nom_mm")
    w("**How does the slewing motion affect residual oscillations?** It puts swing "
      "in a direction a translational shaper is not designed to touch. Unshaped "
      f"radial swing is {un.rad_amp_pp_rad.mean():.3f} rad p-p against "
      f"{un.tan_amp_pp_rad.mean():.3f} rad tangential - the same order of magnitude. "
      "A straight-line move would leave essentially nothing in the cross-axis; here "
      "the centripetal and Coriolis terms of the rotating frame drive the payload "
      "outward along the jib during the slew and it rings radially afterwards. Note "
      "in the table that the single-mode ZV cuts tangential swing to "
      f"{ts[ts.shaper=='ZV'].pct_tan.iloc[0]:.0f} % but leaves radial swing at "
      f"{ts[ts.shaper=='ZV'].pct_rad.iloc[0]:.0f} % - essentially untouched. The "
      "shapers that help radially (ZVD, two-mode ZV, both around 10-30 %) do so "
      "because they smooth the velocity profile far more, not because they target "
      "the radial direction.\n")
    w("**Does the radial distance of the trolley on the jib matter?** Yes, strongly "
      "and monotonically. Unshaped tangential swing grows from "
      f"{un.tan_amp_pp_rad.iloc[0]:.3f} rad at 500 mm to "
      f"{un.tan_amp_pp_rad.iloc[2]:.3f} rad at 900 mm - a factor of "
      f"{un.tan_amp_pp_rad.iloc[2]/un.tan_amp_pp_rad.iloc[0]:.1f} for a 1.8x change "
      "in radius (Figure 09). The same slew rate at a larger radius means a larger "
      "tangential velocity and a larger centripetal acceleration at the payload, so "
      "there is more to excite. What does *not* change is the frequency: f1 and f2 "
      "are identical across radii to within the measurement, because the pendulum "
      "frequencies depend on L1, L2 and the mass ratio, not on where the trolley "
      "sits. That is why one shaper design works at all three radii, and the "
      "percentage reductions in the table are roughly radius-independent while the "
      "absolute amplitudes are not.\n")
    w("**How did slewing (rather than translation) affect the shaper design?** It "
      "did not change the delays, because the mode frequencies are set by the "
      "suspension geometry and are radius-independent - the same impulse times work "
      "everywhere on the jib. What it changed is what a single-mode design can "
      "achieve: the excitation now has a cross-axis component the shaper cannot "
      "cancel, so the useful figure of merit becomes total swing rather than swing "
      "along the direction of travel, and a shaper that broadly smooths the command "
      "beats one that puts a deep notch at exactly one frequency.\n")
    best = ts.sort_values("tan_amp_pp_rad").iloc[0]
    w("**Which shaper is best, and why?**\n")
    w(md_table(ts, ["shaper", "shaper_dur_s", "pct_tan", "pct_tan_m1", "pct_tan_m2",
                    "pct_rad"]))
    w("")
    w("Read that table with Figures 07, 10 and 12 together:\n")
    w("- **ZV** is the cheapest (0.84 s added) but the weakest: mode 1 only to "
      f"{ts[ts.shaper=='ZV'].pct_tan_m1.iloc[0]:.0f} %, and mode 2 to "
      f"{ts[ts.shaper=='ZV'].pct_tan_m2.iloc[0]:.0f} % - i.e. slightly *worse* than "
      "unshaped, exactly as a single-mode design predicts (Figure 12 shows it has no "
      "notch at w2). **These three trials also need a caveat you should check against "
      "your lab notes.** In all three, the logged *actual* slew velocity sits at "
      "~32.3 deg/s throughout, including during both intervals where the logged "
      "command asks for 16.2 deg/s, and the crane travelled 157 deg against a "
      "commanded 130 deg (Figure 07, top right). Either the half-amplitude steps "
      "were not applied to the drive, or this group's motion log is mis-scaled - "
      "note it is also the group carrying the x100 command-scale glitch. The vision "
      "block, and therefore the swing amplitudes, is a separate stream and is "
      "unaffected; it is the ZV trials' *geometry* (travel, tf, tracking) that is "
      "not trustworthy. Say what was measured and flag the ambiguity rather than "
      "asserting the shaping failed.")
    w("- **ZVD as run** gives the lowest tangential number in the table "
      f"({ts[ts.shaper=='ZVD'].pct_tan.iloc[0]:.0f} %), but it is the least "
      "trustworthy result: the amplitudes were mis-entered as [0.25, 0.50, 0.50] "
      "(same error as the bridge), the command therefore asked for 40.5 deg/s "
      "against a ~34 deg/s rate limit and **saturated**, and the crane travelled "
      "144 deg against a commanded 163 deg. It also leaves mode 2 at "
      f"{ts[ts.shaper=='ZVD'].pct_tan_m2.iloc[0]:.0f} %.")
    w("- **Two-mode ZV** is the one to argue for. It is the only shaper executed "
      "exactly as designed - Figure 07 shows the actual velocity tracking all four "
      "0.25 steps cleanly, with no saturation and no command/velocity disagreement - "
      "the only one that moves the "
      "same 129 deg as the unshaped baseline (so its comparison is clean), and the "
      "only one that suppresses **both** modes: mode 1 to "
      f"{ts[ts.shaper=='Two-mode ZV'].pct_tan_m1.iloc[0]:.0f} % and mode 2 to "
      f"{ts[ts.shaper=='Two-mode ZV'].pct_tan_m2.iloc[0]:.0f} %, with radial swing "
      f"at {ts[ts.shaper=='Two-mode ZV'].pct_rad.iloc[0]:.0f} %. Its cost is "
      "duration: 1.11 s of added move time, about the same as the three-impulse "
      "shaper and 0.27 s more than the ZV.\n")
    w("The trade-off to state explicitly: a single-mode ZV is short but leaves the "
      "second mode entirely, and on a double pendulum that second mode is what you "
      "see and hear. Buying two-mode coverage costs roughly the duration of one "
      "extra half-period of the fast mode - cheap, because T2/2 is only "
      f"{tt.T2_theory_s.mean()/2:.2f} s.\n")

    # ------------------------------------------------------------ caveats ---
    w("---\n\n## Caveats to carry into the text\n")
    w("1. **The two tower streams are simultaneous, not consecutive.** The motion "
      "stream and the vision stream record the same window on clocks offset by "
      "~21.2 s, and they are told apart by which columns are populated rather than "
      "by a time gap (a gap-based split fails on 5 of the 12 workbooks). Aligning "
      "them is what lets the residual be scored after the move; an earlier version "
      "of this analysis mis-read the offset as a 15 s delay and reported peak "
      "swing DURING the move as though it were residual. Tower and bridge amplitudes "
      "are still not comparable to each other.")
    w("2. **The ZVD trials on both rigs used [0.25, 0.50, 0.50].** Report them as "
      "the three-impulse shaper that was actually run, not as ZVD.")
    w("3. **Move distance is not constant across shapers.** On the bridge, ZVD moved "
      "371 mm vs 291 mm for ZV at the same tf; on the tower, ZV travelled 157 deg "
      "and ZVD 144 deg vs 129 deg unshaped. Part of any residual difference is a "
      "move-distance difference, which Part A proves matters a great deal.")
    n_short = int((~bt.good_for_plots).sum())
    w(f"4. **{n_short} of {len(bt)} bridge trials recorded fewer than 3 residual "
      "cycles** because the return move came too soon, against the 4-5 the handout "
      "asks for. They are consistent with the rest but are the weakest evidence; "
      "`good_for_plots` in `bridge_trials.csv` marks them and the figures prefer "
      "trials with long windows.")
    w(f"5. **{int((~ib.use).sum())} of {len(ib)} bridge files were set aside** - "
      "byte-identical duplicates and two mislabelled files caught by the in-file "
      "cable-length tag. See DATA_QUALITY.md before citing any file by name.")
    w("6. **The three tower ZV trials' motion log is questionable** - logged actual "
      "velocity ignores the logged half-amplitude command steps, and travel exceeds "
      "the commanded area by 1.21x. Their swing amplitudes (a separate data stream) "
      "are fine; their travel/tf/tracking numbers are not. Check against lab notes.")
    w("7. **The velocity-based residual prediction is quantitative on the bridge but "
      "only indicative on the tower.** The tower runs at tf/T1 ~ 2.1-2.5, where the "
      "pulse frequency response turns over fast, so the 10-16 % frequency error "
      "moves the prediction by up to 8x. `tower_tracking.csv` reports it at both the "
      "model and measured frequencies so the spread is visible.")
    w("8. **One tower recording (16:55:03) starts mid-move**, so its slew travel is "
      "85 deg instead of 129 deg and its impulse delays could not be read back. Its "
      "residual swing is still usable; it is marked in `tower_trials.csv` and "
      "crossed out in Figure 09.")
    w("9. **Measured tower mode frequencies are 10-16 % below the linearised "
      "double-pendulum model**, so every tower shaper was detuned by that much. "
      "This is the main reason no tower shaper reaches the near-zero residual the "
      "model promises.\n")

    w("---\n\n## Figure index\n")
    figs = [
        ("fig01_partA_time_histories.png", "Part A", "unshaped vs ZV payload deflection at each tf"),
        ("fig02_partA_residual_vs_tf.png", "Part A", "residual vs tf against the pulse's frequency response - the move-distance explanation"),
        ("fig03_partB_time_histories.png", "Part B", "unshaped vs ZV vs ZVD at each cable length"),
        ("fig04_partB_residual_vs_cable.png", "Part B", "residual vs cable length, measured and predicted"),
        ("fig05_sensitivity_curves.png", "Part B", "sensitivity curves with the three test frequencies - the design justification"),
        ("fig06_bridge_velocity_profiles.png", "Part B", "applied velocity staircases read back from the data, showing the ZVD amplitude error"),
        ("fig07_tower_command_tracking.png", "Tower", "command vs actual slew velocity - execution quality per shaper"),
        ("fig08_tower_swing_time_histories.png", "Tower", "tangential and radial swing traces"),
        ("fig09_tower_residual_vs_radius.png", "Tower", "residual vs trolley radius"),
        ("fig10_tower_mode_split.png", "Tower", "residual split by mode - the two-mode argument"),
        ("fig11_tower_spectra.png", "Tower", "swing spectra with both predicted modes marked"),
        ("fig12_tower_sensitivity.png", "Tower", "tower shaper sensitivity curves with both modes marked"),
        ("fig13_shaper_target_frequencies.png", "Both", "shaper sensitivity vs frequency for both cranes with each shaper's target frequency marked - minimal labelling, written to be captioned"),
    ]
    w("| figure | section | message |")
    w("|---|---|---|")
    for f, sec, msg in figs:
        w(f"| `{f}` | {sec} | {msg} |")
    w("")
    w("The handout limits you to 3 pages of text and asks for non-redundant plots. A "
      "minimal set that covers every required discussion point: **02** (Part A "
      "trend), **03** or **04** (Part B comparison), **05** (Part B design "
      "justification), **07** (tower execution), **10** (tower two-mode argument). "
      "Figures 01, 06, 08, 09, 11 and 12 are supporting material.\n")

    with open(OUT, "w") as fh:
        fh.write("\n".join(A))
    print("wrote", os.path.relpath(OUT, L.ROOT))
    return OUT


if __name__ == "__main__":
    main()
